Меркулова Надежда, вариант 4
frontend-park-mail-ru/frontend-homework0-2 pull request #11
Opened 2019-03-09 15:46 UTC by crueltycute

2019-03-10 21:42 UTC, n-parpibaeva requested changes

2019-03-10 21:42 UTC, n-parpibaeva commented on static/css/login.css
> +body {
Вот эти стили у тебя в каждом файле, давай вынесем в отдельный, например, ```common-css```)

2019-03-10 21:42 UTC, n-parpibaeva commented on static/login.html
> +                <input class="login-row__input" placeholder="Пароль"/>
type=password

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/login.html
> +                <input class="login-row__input" placeholder="Пароль"/>
login-row__input меньше контейнера, сложно попасть курсором для редактирования)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/login.html
> +                <input class="login-row__input" placeholder="Пароль"/>
к инпуту хорошо бы привязать label
[тут примерчики](https://developer.mozilla.org/ru/docs/Web/HTML/Element/label#Examples)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/login.html
> +                <div class="provider provider_fb">
это ссылка, нужен другой тег)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/login.css
> +    margin-right: -50%;
оно и без этого отцентрируется)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/login.css
> +    input::placeholder {
почему селектор для input, у него же есть класс?)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/login.css
> +    .login-header__btn-close {
лучше position: absolute и смещение какое-то

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/login.css
> +.login__btn-enter {
давай стиль для hover добавим)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/update-profile.css
> +        .dialog-content__header {
форматирование поехало :(

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/signup.html
> +        <div class="sign-up__info-requester">Для регистарции на ресурсе укажите инфомацию о себе</div>
регистарции
ошибочка)

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/signup.html
> +        <input class="sign-up__row" type="text" placeholder="Фамилия">
Давай добавим label для каждого input

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/signup.html
> +            <div class="unit phone-unit phone-unit_number">
телефон нельзя ввести :(

2019-03-10 21:42 UTC, Thewhiterabbit123 commented on static/css/update-profile.css
> +    margin-right: -50%;
и без него выровняется)

2019-03-11 11:41 UTC, crueltycute commented
работает в chrome, safari и firefox :)

2019-05-02 12:14 UTC, vileven commented
**Привет!**

5 баллов + 1 бал за кроссбраузерность и +1 бал за современный CSS

2019-06-02 09:06 UTC, closed without merging