Котов Никита, вариант 11
frontend-park-mail-ru/frontend-homework0-2 pull request #12
Opened 2019-03-25 17:33 UTC by Kotyarich

2019-03-26 15:30 UTC, kirill-gadzhiev requested changes
Постарайся использовать более емкие имена для css-классов. По компонентам, по модификатору. 

Также почитай про семантические теги, они позволяют поисковикам лучше индексировать твои страницы, а также помогают людям с ограниченными возможностями, которые пользуются специальным инструментами для воспроизведения веб-страниц.

Конечно, у тебя есть повторения в коде, которые можно было бы заменить на импорты, но в данном случае при копипасте кода в систему проверки будет сложно, так что тут претензий нет. Другое дело с цветами, например. Ты их используешь много раз даже внутри одного файла. Так что было бы целесообразно вынести их в [css-переменные](https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties).

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/login.css
> +svg {
Плохо писать селекторы только по тегу. Лучше использовать класс или комбинацию класса и тега

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/login.html
> +            <span class="header-text"><strong>Логин</strong></span>
Если используешь стандартный тег - полагаешься на то, что во всех браузерах будет отображаться одинаково. Лучше опять же навешивать свой класс и задавать явно стиль. 
Хорошо, что используешь strong, он подчеркивает **важность** текста, а не просто делает жирным.

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/login.html
> +                Войти через Вконтакте
Лучше стараться оборачивать текстовые ноды в элементы, чтобы если потребуется оставалось навесить только класс, а также чтобы проще выбирать элемент из js.

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/menu.css
> +    float: left;
float уже считается не лучшей практикой, лучше стараться его избегать. Попробуй сделать без его использования.

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/menu.css
> +    padding: 5.8% 2%;
не думаю, что это лучший способ задавать отступы. Посмотри в сторону других единиц измерения.

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/menu.css
> +.first-input {
на десять трок выше определен этот же класс с этим же свойством.

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/login.css
> +    height: 10.41%;
Очень странный размер. Да и для высоты лучше не использовать %, тк она [вычисляется рекурсивно](https://learn.javascript.ru/height-percent). 
Это же кнопка. Почему она зависит от родителя? Я понимаю от контента, либо от заданных заранее форматов кнопки (маленькая, стандартная, большая). А так получается неконсистентный дизайн

2019-03-26 15:30 UTC, kirill-gadzhiev commented on static/menu.css
> +.white {
Вот тут опять же. Что может значить .white, когда мы видим это в html. Цвет фона, рамки, текста?

2019-03-26 15:30 UTC, kirBMSTU commented on static/menu.css
> +    float: left;
у флексбокса есть масса свойств для позиционирования и их достаточно, постарайся убрать float)

2019-03-26 15:30 UTC, kirBMSTU commented on static/profile.css
> +.right {
тут комент, аналогичный .white.
Плюс вот еще что. Если это просто right, почему у него еще и width задано?))
Отсюда опять же вытекает следствие, что надо отталкиваться от компонентов и их модификаторов. БЭМ, в общем.

2019-03-26 15:30 UTC, kirBMSTU commented on static/profile.css
> +.type {
опять же, только посмотрев в html я понял, что этот класс вешается на блок, в котором пишется название поля. Лучше же назвать тогда field-type. Либо если по БЭМу, то тк этот блок внутри .field,  
то field__field-type

2019-05-31 09:08 UTC, vileven commented
Привет! 5 баллов +доп.  балл за адаптивность!

2019-05-31 09:09 UTC, closed without merging