APO-21_Prokopenko_Variant-6
frontend-park-mail-ru/frontend-homework0-2 pull request #13
Opened 2019-03-26 00:37 UTC by rowbotman

2019-03-26 21:43 UTC, kirill-gadzhiev requested changes
Что-то с отступами, встречаются разные отступы в одном классе, и в разных. В html тоже перепроверь.

Почитай про семантические теги, которые повышают доступность. Это влияет на индексирование поисковиками и парсинг страниц специальными читалками для людей с ограниченными возможностями

Кнопка "Войти" слишком маленькая, бросается в глаза

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/common.css
> +.btn-3 {
что значат эти цифры после дефиса?

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/login.css
> +	float: right;
постарайся не использовать float. Он уже устаревший и его применение - не лучшая практика

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/login.css
> +.tick-box input:checked ~ .checkmark:after {
Вот такие сложные селекторы плохо влияют на производительность. Плюс они сильно увеличивают связность элементов, что не очень хорошо, тк элемент зависит от своего окружения. Если делать по БЭМу, то делаешь модификатор и вешаешь класс через js. В данном случае js не используется, можно оставить что-то подобное или сразу повесить в html класс для отмеченного чекбокса и атрибут checked, тем самым сымитировав логику js.

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/login.css
> +.container-2 {
как и с кнопкой, непонятная цифра в названии

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/login.css
> +	color: #ced4;
принято задавать hex код цвета либо 3, либо 6 значным кодом. Плюс селектор по тегу это не круто. Используй класс или комбинацию класса и тега, если очень хочется)

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/menu.css
> +.bar-10 {
тут меня уже посещают мысли, что я не шарю, и это какая-то сложная бизнес логика именования классов. Напиши потом, что это)

2019-03-26 21:43 UTC, kirill-gadzhiev commented on templates/css/register.css
> +	margin-top: 3%;
У вас же по условию отступы между элементами кратны 4, а падинги 5.

2019-03-26 21:43 UTC, kirBMSTU commented on templates/css/common.css
> +	font-family: Helvetica;
Лучше шрифт вынести в body, тк он один для всего. Еще лучше задавать набор шрифтов на тот случай, если у клиента в системе нет какого-то шрифта.

2019-03-26 21:43 UTC, kirBMSTU commented on templates/css/common.css
> +	box-shadow: 0 0 40px -5px rgba(0,0,0,0.5);
Цвета можно вынести в [css-переменные](https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties), тк они часто повторяются

2019-05-31 09:07 UTC, vileven commented
**Привет!**
Молодец, 5 баллов.

2019-05-31 09:08 UTC, closed without merging