Владимир Северов
frontend-park-mail-ru/frontend-homework0-2 pull request #7
Opened 2019-02-24 13:31 UTC by hackallcode

2019-02-24 13:34 UTC, hackallcode commented
Можно посмотреть воочию на сайте:
https://front.hackallcode.ru

2019-02-24 14:48 UTC, SinimaWath requested changes
Привет :) Глянул пока Регистрацию. Выглядит норм 👍 Поправь пока эти замечания

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Хорош!

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +<html lang="en">
Так у нас язык ru, а тут стоит en. Для скрин ридеров это проблемка, он не сможет нормально прочитать русские символы

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +            <input class="button" type="email" title="Email" placeholder="Email">
Оставлять input без label плохая практика для Доступности. Лучше повесь aria-label или сделай label, но спрячь его, [почитай](https://www.w3.org/WAI/tutorials/forms/labels/)

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +            <input class="button" type="password" title="Password" placeholder="Пароль">
Почему у input, всех button класс?

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +            <button class="button register" type="submit">Зарегистрироваться</button>
А вот эта кнопка из интерфейса, как-будто бы не кликабельна :) может тебе поможет cursor: ...

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +            <div class="right-icon hide"></div>
Ой, а вот это кликабельынй элемент, а с клавиатуры его не видно. Попробуй нажимая TAB попасть на него

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +<div class="bg-image"></div>
Может вынести это в свойство body?

2019-02-24 14:48 UTC, SinimaWath commented on layouts/img/icons/actions/delete.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
Не оптимизированные svg-ки. Оптимизируй их, к примеру, из svgo

2019-02-24 14:48 UTC, SinimaWath commented on layouts/css/var8_signup.css
> +@media (max-height: 500px) {
Выглядит, ужасно, при <=500.  Может сделаешь по другому?

2019-02-24 14:48 UTC, SinimaWath commented on layouts/css/var8_signup.css
> +.signup-holder .btn-holder.error .error-msg {
Зачем тебе это?

2019-02-24 14:48 UTC, SinimaWath commented on layouts/css/var8_signup.css
> +    display: none;
Если хочешь скрывать элемент, делаю отдельный атрибут для этого, к примеру, hidden

2019-02-24 14:48 UTC, SinimaWath commented on layouts/var8_signup.html
> +            <input class="button" type="email" title="Email" placeholder="Email">
title тоже не всегда спасает :)

2019-02-24 15:05 UTC, SinimaWath commented
![image](https://user-images.githubusercontent.com/11785873/53300993-9d616d80-385e-11e9-9269-63b4e2af3e7f.png)
вот пример, почему использовать em для всего плохая и нечитаемая практика.
Используй em только для padding marging font-size

2019-02-24 17:32 UTC, SinimaWath commented
Давай добавим современные теги из HTML5(aside, section, article, main. header, footer) во все макеты. Заюзай там, где ты считаешь нужно user-select: none (прочитай если не знаешь).  И в основом замечания к Регистрации аналогичны и в других макетах, так что тоже исправь их

2019-02-24 17:35 UTC, SinimaWath commented on layouts/var8_signup.html
> +    <div class="label">Наше невероятно красивое приложение, в котором вы обязаны зарегистрироваться.</div>
На странице всегда должен быть h1

2019-02-24 17:39 UTC, SinimaWath commented on layouts/var8_update-profile.html
> +                <div class="label">Email</div>
Зачем придумывать что-то, если уже есть тэг label?

2019-02-24 17:39 UTC, SinimaWath commented on layouts/var8_update-profile.html
> +                <div class="label">Телефон</div>
Аналогично, есть label

2019-02-24 17:41 UTC, SinimaWath commented on layouts/css/var8_update-profile.css
> +@media (max-height: 500px) {
Зачем на маленьких экранах, прибиваешь к верху?

2019-02-24 18:40 UTC, hackallcode commented on layouts/var8_signup.html
> +<div class="bg-image"></div>
Тогда не будет, как на скринах, отступа по бокам от картинки с:

2019-02-24 18:47 UTC, SinimaWath commented on layouts/var8_signup.html
> +<div class="bg-image"></div>
Не думаю, что она нужна :)

2019-02-24 19:58 UTC, SinimaWath commented on layouts/css/var8_menu.css
> +    background: #CA9CF4 !important;
Very bad практика. !important только для переопределения стилей различных либ. Если в твоем же коде есть !important => у тебя проблемы с модульностью, исправь

2019-02-24 19:58 UTC, SinimaWath commented on layouts/css/var8_menu.css
> +    height: 100vh;
Почему 100vh, а не 100%?

2019-02-24 20:16 UTC, SinimaWath commented on layouts/css/var8_menu.css
> +    margin-top: 24%;
Ты знаешь 24% от чего?

2019-02-24 20:19 UTC, hackallcode commented on layouts/var8_signup.html
> +            <div class="right-icon hide"></div>
У меня видно...

2019-02-24 20:44 UTC, hackallcode commented on layouts/css/var8_update-profile.css
> +@media (max-height: 500px) {
Если на мобильном откроется клавиатура, то пригодится скрол

2019-02-24 20:44 UTC, hackallcode commented on layouts/css/var8_signup.css
> +    display: none;
Там  класс "error" одновременно меняет цвет поля и отображает ошибку

2019-02-24 21:00 UTC, hackallcode commented on layouts/css/var8_menu.css
> +    height: 100vh;
Потому что 100% работать не будет, потому что body автоматически подгоняется под контент

2019-02-24 21:00 UTC, hackallcode commented on layouts/css/var8_menu.css
> +    margin-top: 24%;
Да, от ширины

2019-02-25 06:54 UTC, SinimaWath requested changes

2019-02-25 06:54 UTC, SinimaWath commented on layouts/var8_menu.html
> +<nav class="menu-holder">
Навигацию, зачастую принято делать списками. Потому что для скрин ридеров div ничего не значит.  https://inclusive-components.design/menus-menu-buttons/

2019-02-27 04:38 UTC, hackallcode commented on layouts/var8_menu.html
> +<nav class="menu-holder">
У меня кнопки, а они читаются ридерами, но сейчас посмотрю, может на стандартные списки заменю

2019-02-28 13:21 UTC, vileven commented
**Привет!**

Отлично постарался. Держи свои *5 балов*. 

А поскольку заморочился с адаптивностью: `@media` и относительными единицами, держи **+1** доп. балл за адаптивность! 

P.S. То что задеплоил – тоже отлично!

2019-02-28 13:22 UTC, closed without merging